export interface DishWithHistory {
  id: number;
  lastCookedAt: string | null;
}

export interface WeightedDish<T extends DishWithHistory> {
  dish: T;
  weight: number;
}

const MAX_WEIGHT = 10;
const DAYS_MULTIPLIER = 0.5;

export function calculateWeights<T extends DishWithHistory>(
  dishes: T[],
  currentDateStr: string // ISO date string of generation time
): WeightedDish<T>[] {
  const currentDate = new Date(currentDateStr).getTime();
  
  return dishes.map(dish => {
    let weight = 1;
    if (!dish.lastCookedAt) {
      // Never cooked: highest priority
      weight = MAX_WEIGHT;
    } else {
      const lastCooked = new Date(dish.lastCookedAt).getTime();
      const diffTime = currentDate - lastCooked;
      const diffDays = Math.max(0, Math.floor(diffTime / (1000 * 60 * 60 * 24)));
      
      // Base weight is 1. Add DAYS_MULTIPLIER for every day since last cooked.
      weight = 1 + (diffDays * DAYS_MULTIPLIER);
      
      if (weight > MAX_WEIGHT) {
        weight = MAX_WEIGHT;
      }
    }
    
    return { dish, weight };
  });
}

/**
 * Selects randomly based on weights.
 * @param weightedDishes List of dishes with their weights
 * @param randomValue A value strictly in [0, 1) generated by a random function
 */
export function weightedRandomSelect<T extends DishWithHistory>(
  weightedDishes: WeightedDish<T>[],
  randomValue: number
): T | null {
    if (weightedDishes.length === 0) return null;
    
    const totalWeight = weightedDishes.reduce((sum, wd) => sum + wd.weight, 0);
    if (totalWeight === 0) return weightedDishes[0]!.dish;
    
    let currentWeight = 0;
    const target = randomValue * totalWeight;
    
    for (const wd of weightedDishes) {
        currentWeight += wd.weight;
        if (currentWeight >= target) {
            return wd.dish;
        }
    }
    return weightedDishes[weightedDishes.length - 1]!.dish;
}
